import { AppError } from "../../common/errors/AppError.js";
import { prisma } from "../../loaders/dbLoader.js";
import { ROLES } from "../../common/constants/roles.js";
import { findTeamByLeaderId, findTeamMemberByUserId, teamUserSelect } from "../teams/teams.repository.js";
import { exchangeGoogleCalendarCode, exchangeMicrosoftCalendarCode, getGoogleCalendarAuthUrl, getMicrosoftCalendarAuthUrl, verifyCalendarOAuthState } from "./calendar.providers.js";
import { syncMeetingService } from "../meetings/meetings.service.js";
const buildFullName=(u)=>`${u?.firstName??""} ${u?.lastName??""}`.trim();
async function getRelevantTeamIds(actor){if(actor.role===ROLES.ADMIN){return (await prisma.team.findMany({select:{id:true}})).map(t=>t.id);} if(actor.role===ROLES.LEADER){const team=await findTeamByLeaderId(actor.id); return team?[team.id]:[];} if(actor.role===ROLES.STUDENT){const m=await findTeamMemberByUserId(actor.id); return m?.team?[m.team.id]:[];} return (await prisma.team.findMany({where:actor.role===ROLES.DOCTOR?{doctorId:actor.id}:{taId:actor.id},select:{id:true}})).map(t=>t.id);}
const normalizeDateBoundary=(value,end=false)=>{if(!value) return null; const date=new Date(value); if(Number.isNaN(date.getTime())) return null; if(!String(value).includes('T')){if(end) date.setHours(23,59,59,999); else date.setHours(0,0,0,0);} return date;};
export const getCalendarConnectUrlService=(actor,provider)=>provider==="GOOGLE"?getGoogleCalendarAuthUrl(actor.id):provider==="OUTLOOK"?getMicrosoftCalendarAuthUrl(actor.id):(()=>{throw new AppError("Unsupported calendar provider.",422,"CALENDAR_PROVIDER_UNSUPPORTED");})();
const buildCallbackRedirect=(provider,status,message="")=>`${(process.env.FRONTEND_URL||"http://localhost:3000").replace(/\/+$/,'')}/dashboard/calendar?${new URLSearchParams({provider,status,message}).toString()}`;
export async function handleGoogleCalendarCallbackService(code,state){const userId=verifyCalendarOAuthState(state,"GOOGLE"); const data=await exchangeGoogleCalendarCode(code); await prisma.calendarIntegration.upsert({where:{userId_provider:{userId,provider:"GOOGLE"}},update:{...data,syncEnabled:true},create:{...data,userId,syncEnabled:true}}); return buildCallbackRedirect("google","connected","Google Calendar connected.");}
export async function handleMicrosoftCalendarCallbackService(code,state){const userId=verifyCalendarOAuthState(state,"OUTLOOK"); const data=await exchangeMicrosoftCalendarCode(code); await prisma.calendarIntegration.upsert({where:{userId_provider:{userId,provider:"OUTLOOK"}},update:{...data,syncEnabled:true},create:{...data,userId,syncEnabled:true}}); return buildCallbackRedirect("outlook","connected","Outlook Calendar connected.");}
export async function listCalendarIntegrationsService(actor){const integrations=await prisma.calendarIntegration.findMany({where:{userId:actor.id},orderBy:{provider:"asc"}}); return integrations.map(i=>({id:i.id,provider:i.provider,email:i.email,displayName:i.displayName,syncEnabled:i.syncEnabled,lastSyncedAt:i.lastSyncedAt,lastSyncStatus:i.lastSyncStatus,lastSyncError:i.lastSyncError,createdAt:i.createdAt,updatedAt:i.updatedAt}));}
export async function disconnectCalendarIntegrationService(actor,provider){const integration=await prisma.calendarIntegration.findUnique({where:{userId_provider:{userId:actor.id,provider}}}); if(!integration) throw new AppError("Calendar integration not found.",404,"CALENDAR_INTEGRATION_NOT_FOUND"); const updated=await prisma.calendarIntegration.update({where:{id:integration.id},data:{syncEnabled:false,lastSyncStatus:"DISCONNECTED",lastSyncError:null}}); return {id:updated.id,provider:updated.provider,syncEnabled:updated.syncEnabled,lastSyncStatus:updated.lastSyncStatus};}
const calendarMeetingInclude={team:{select:{id:true,name:true,leader:{select:teamUserSelect},doctor:{select:teamUserSelect},ta:{select:teamUserSelect},members:{select:{user:{select:teamUserSelect}}}}},organizer:{select:teamUserSelect},participants:{include:{user:{select:teamUserSelect}}},approvals:{include:{approver:{select:teamUserSelect}}}};
function mapMeetingToCalendarEvent(meeting,actor){return {id:`meeting:${meeting.id}`,sourceType:"MEETING",sourceId:meeting.id,title:meeting.title,description:meeting.description,startAt:meeting.startAt,endAt:meeting.endAt,status:meeting.status,mode:meeting.mode,provider:meeting.provider,externalProvider:meeting.externalProvider,location:meeting.location,joinUrl:meeting.joinUrl,team:{id:meeting.team.id,name:meeting.team.name},organizer:{id:meeting.organizer.id,fullName:buildFullName(meeting.organizer),email:meeting.organizer.email,role:meeting.organizer.role},participants:meeting.participants.map(p=>({id:p.id,userId:p.userId,email:p.user?.email||p.email,displayName:p.user?buildFullName(p.user):p.displayName||p.email,participantRole:p.participantRole,responseStatus:p.responseStatus,canApprove:p.canApprove,isExternalGuest:p.isExternalGuest})),approvals:meeting.approvals.map(a=>({id:a.id,approverUserId:a.approverUserId,approverRole:a.approverRole,status:a.status,proposedStartAt:a.proposedStartAt,proposedEndAt:a.proposedEndAt,note:a.note,respondedAt:a.respondedAt,approverName:a.approver?buildFullName(a.approver):null})),permissions:{isOrganizer:meeting.organizerId===actor.id,canManage:actor.role===ROLES.ADMIN||meeting.organizerId===actor.id||(actor.role===ROLES.LEADER&&meeting.team.leader?.id===actor.id),canApprove:meeting.approvals.some(a=>a.approverUserId===actor.id&&["PENDING","PROPOSED_NEW_TIME"].includes(a.status)),canRespond:meeting.participants.some(p=>p.userId===actor.id)},externalSyncStatus:meeting.externalSyncStatus,externalSyncError:meeting.externalSyncError,confirmedAt:meeting.confirmedAt,updatedAt:meeting.updatedAt};}
const mapTaskToCalendarEvent=(task)=>({id:`task:${task.id}`,sourceType:"TASK_DEADLINE",sourceId:task.id,title:`Task deadline • ${task.title}`,description:task.description,startAt:task.dueDate,endAt:task.dueDate,allDay:true,status:task.status,priority:task.priority,team:{id:task.team.id,name:task.team.name},assignee:task.assignee?{id:task.assignee.id,fullName:buildFullName(task.assignee),email:task.assignee.email,role:task.assignee.role}:null});
export async function listCalendarEventsService(actor,query={}){const teamIds=await getRelevantTeamIds(actor); const startAt=normalizeDateBoundary(query.start); const endAt=normalizeDateBoundary(query.end,true); const meetingWhere={AND:[]}; if(teamIds.length) meetingWhere.AND.push({teamId:{in:teamIds}}); if(startAt) meetingWhere.AND.push({endAt:{gte:startAt}}); if(endAt) meetingWhere.AND.push({startAt:{lte:endAt}}); if(actor.role===ROLES.DOCTOR||actor.role===ROLES.TA) meetingWhere.AND.push({OR:[{organizerId:actor.id},{participants:{some:{userId:actor.id}}},{approvals:{some:{approverUserId:actor.id}}}]}); const meetings=teamIds.length?await prisma.meeting.findMany({where:meetingWhere.AND.length?meetingWhere:undefined,include:calendarMeetingInclude,orderBy:{startAt:"asc"}}):[]; const tasks=teamIds.length?await prisma.task.findMany({where:{teamId:{in:teamIds},dueDate:{...(startAt?{gte:startAt}:{}),...(endAt?{lte:endAt}:{})}},include:{team:{select:{id:true,name:true}},assignee:{select:teamUserSelect}},orderBy:{dueDate:"asc"}}):[]; return [...meetings.map(m=>mapMeetingToCalendarEvent(m,actor)),...tasks.map(mapTaskToCalendarEvent)].sort((a,b)=>new Date(a.startAt).getTime()-new Date(b.startAt).getTime());}
export async function syncCalendarProviderService(actor,provider,payload={}){const providerKey=provider==="google"||provider==="GOOGLE"?"GOOGLE":provider==="outlook"||provider==="OUTLOOK"?"OUTLOOK":null; if(!providerKey) throw new AppError("Unsupported calendar provider.",422,"CALENDAR_PROVIDER_UNSUPPORTED"); const integration=await prisma.calendarIntegration.findUnique({where:{userId_provider:{userId:actor.id,provider:providerKey}}}); if(!integration||!integration.syncEnabled) throw new AppError("Connect this calendar provider first.",400,"CALENDAR_CONNECT_REQUIRED"); if(payload.meetingId) return syncMeetingService(actor,payload.meetingId); const upcomingMeetings=await prisma.meeting.findMany({where:{organizerId:actor.id,externalProvider:providerKey,status:"CONFIRMED",startAt:{gte:new Date(Date.now()-86400000)}},select:{id:true},orderBy:{startAt:"asc"},take:25}); const synced=[]; for(const meeting of upcomingMeetings) synced.push(await syncMeetingService(actor,meeting.id)); await prisma.calendarIntegration.update({where:{id:integration.id},data:{lastSyncedAt:new Date(),lastSyncStatus:"SYNCED",lastSyncError:null}}); return synced;}
